### ISSUE TITLE
MoveAxesAsync Generating Incorrect G-Code for Z-Axis Moves

### ISSUE THREAD

**Issue by JerrettDavis** [AndreasReitberger/KlipperRestApiSharp#16]
Looking at the code, it looks like the `MoveAxesAsync` method is incorrectly generating the gcode for Z-axis moves. Instead of using `Z` in the gcode, `Y` has been inserted. You can view the problem here: 

https://github.com/AndreasReitberger/KlipperRestApiSharp/blob/b3e5604758cc137fbb790aed3a34a0d78c479af9/source/MoonrakerSharpWebApi/MoonrakerSharpWebApi/MoonrakerClient.cs#L5660

**Comment by AndreasReitberger** [comment]
Hi @jerretDavis

Thank you for the hint and the PR to fix it 😊
