### ISSUE TITLE
Attempting to move multiple axes with MoveAxesAsync only results in X movement

### ISSUE THREAD

**Issue by JerrettDavis** [AndreasReitberger/KlipperRestApiSharp#18]
If you attempt to move the toolhead to a new position by manipulating multiple axes at once, only the X axis will move. 

Here's an example of a call that will result only in X movement.

```csharp
var moved = await _server.MoveAxesAsync(
    speed: 6000, 
    x: newX, 
    y: newY, 
    z: newZ,
    relative: false);
```

**Comment by AndreasReitberger** [comment]
Hi @JerrettDavis 
once again, thank you very much for your contribution.
I have no access to the running moonraker server at the moment, however I assume the test has passed with the new movement function?
If so, I will merge the PR right away.

**Comment by JerrettDavis** [comment]
Hi @AndreasReitberger,
I was able to confirm that the tests were successfully executed on my local moonraker instance, and the machine responded as expected.
