### ISSUE TITLE
App doesn’t connect to webcam

### ISSUE THREAD

**Issue by adrianocr** [AndreasReitberger/KlipperRestApiSharp#4]
If I load up fluidd in a browser or use another iOS app like mobileraker the webcam shows correctly. But on RC klipper 3D the webcam doesn’t load. It connects to the server and printer, and everything else works. But the webcam doesn’t

**Comment by AndreasReitberger** [comment]
Thank you very much for your bug report.
I'll check it with fluiddPi and release a fix.
Do you see any error log in the Event Manager page?
If so, please share it here.

Best,
Andreas

**Comment by AndreasReitberger** [comment]
Hi @adrianocr 
I just switched my print server to FluiddPi and tested the webcam with the latest version available on the App Store.
On my end, it's working fine.
Can you attach a screenshot of the webcam page?

Just to be sure, there is a small icon in the upper right corner. There, you can switch between print image and webcam stream.
Maybe it's set to the print image?

![image](https://user-images.githubusercontent.com/2952443/189515929-06073c40-a3c6-4286-b58e-aeb06df73f55.png)

**Comment by adrianocr** [comment]
Yeah check these two pics out:
![C40B83DF-D0A6-4EF3-A6E4-AB3B9F79190C](https://user-images.githubusercontent.com/7603338/189998282-464256d8-57a2-45b5-be5f-d9306b46ee1e.png)
![704ED4B4-7E76-49A2-A3AF-7F92D262E47F](https://user-images.githubusercontent.com/7603338/189998290-7df4eb2d-403c-424e-992c-c4038d7c23b9.png)

It works fine if I open fluidd in my browser and also using the Mobileraker app. But fails in rc klipper 3D. 

My setup is in docker containers utilizing [mkuf/prind](https://github.com/mkuf/prind) so maybe it’s an issue there? But I don’t know if that makes sense because like I said it works fine via the browser and through mobileraker

**Comment by adrianocr** [comment]
And I have a bunch of warnings and errors in the event logs, see pics:

![5CBECD2F-D806-4F22-BFCA-C86DB2561F16](https://user-images.githubusercontent.com/7603338/190000776-a9960713-e127-4d31-aa25-30357bb2ed1b.png)
![4AE3D937-6CC6-463B-99C5-6AC9CDE4C3DA](https://user-images.githubusercontent.com/7603338/190000783-5f7f5155-29c7-4b90-ace2-a32861fc62b1.png)

**Comment by AndreasReitberger** [comment]
@adrianocr 
Thanks for sharing your screenshots. In the first one, with the black background, the webcam should be running.
At least the app settings for it are fine.
Can you share your webcam config from FluiddPi?

Warnings are fine, the errors will be addressed. I'm currently working on the update and fixed those errors with the "cpu_temp" conversion already.

I hope to get an update ready this weekend.

**Comment by adrianocr** [comment]
@AndreasReitberger I'm not actually using fluiddpi, I'm running klipper, moonraker, and fluidd in individual docker containers. So if your question is specifically fluiddpi related then I can't really answer it.

But having said that, I've tried two ways; 1) via the moonraker.cfg file, and through the fluidd UI. Neither of them seem to work with RC Klipper 3D. Screenshots:

![fluidd Configuration 2022-09-14 at 11 54 25 AM](https://user-images.githubusercontent.com/7603338/190203615-06351b1a-349d-46a9-bd6d-c9448141a79a.jpg)

![fluidd Settings 2022-09-14 at 11 56 27 AM](https://user-images.githubusercontent.com/7603338/190203864-6ab7068e-08d5-441f-9320-1c32dd7ecc99.jpg)

**Comment by adrianocr** [comment]
Also it may be worth pointing out that the camera list in RC Klipper 3D doesn’t populate any cameras in the drop-down list: 
![815C00FE-190A-43AD-8A79-77D6951734AD](https://user-images.githubusercontent.com/7603338/190207146-d3e07dbe-fa7e-4ba0-b73b-5adddfe9aced.jpeg)

**Comment by AndreasReitberger** [comment]
Hi @adrianocr 
I actually ment the web dashboard provided by fluidd. Maybe FluiddPi was confusing, but you actually posted the right screenshot.

Yes, that the cam list is empty could be a good point to start with.

I'll do some investigating and come back to you.

Thanks for your help!

**Comment by AndreasReitberger** [comment]
Hi @adrianocr 
can you try following commands in your browser and send me the result, please?
You must do this while you are logged in in your dashboard.

Also check if this is your IP.

`http://192.168.0.5/server/database/item?namespace=fluidd&key=cameras`

This should return a JSON object with your cameras. If this doesn't work, add your API key into the query.

`http://192.168.0.5/server/database/item?namespace=fluidd&key=cameras?token=YOUR_API`

Eventually, if the previous commands worked, get the whole settings as JSON string while using this command.

`http://192.168.0.5/server/database/item?namespace=fluidd`

Thank you!

**Comment by adrianocr** [comment]
```
{
  "result": {
    "namespace": "fluidd",
    "key": "cameras",
    "value": {
      "activeCamera": "b2d3a921-987d-4838-a006-31504fbf9588"
    }
  }
}

```
and

```
{
  "result": {
    "namespace": "fluidd",
    "key": null,
    "value": {
      "cameras": {
        "activeCamera": "b2d3a921-987d-4838-a006-31504fbf9588"
      },
      "charts": {},
      "console": {
        "commandHistory": [
          "POWEROFF",
          "SHUTDOWN",
          "SAVE_CONFIG",
          "RESTART",
          "TUNING_TOWER COMMAND=SET_PRESSURE_ADVANCE PARAMETER=ADVANCE START=0 FACTOR=.020",
          "SET_VELOCITY_LIMIT SQUARE_CORNER_VELOCITY=1 ACCEL=500",
          "TUNING_TOWER COMMAND=SET_PRESSURE_ADVANCE PARAMETER=ADVANCE START=0 FACTOR=.020",
          "SET_VELOCITY_LIMIT SQUARE_CORNER_VELOCITY=1 ACCEL=500",
          "TUNING_TOWER COMMAND=SET_PRESSURE_ADVANCE PARAMETER=ADVANCE START=0 FACTOR=.020",
          "SET_VELOCITY_LIMIT SQUARE_CORNER_VELOCITY=1 ACCEL=500",
          "TUNING_TOWER COMMAND=SET_PRESSURE_ADVANCE PARAMETER=ADVANCE START=0 FACTOR=.020",
          "SET_VELOCITY_LIMIT SQUARE_CORNER_VELOCITY=1 ACCEL=500",
          "TUNING_TOWER COMMAND=SET_PRESSURE_ADVANCE PARAMETER=ADVANCE START=0 FACTOR=.020",
          "SET_VELOCITY_LIMIT SQUARE_CORNER_VELOCITY=1 ACCEL=500",
          "TUNING_TOWER COMMAND=SET_PRESSURE_ADVANCE PARAMETER=ADVANCE START=0 FACTOR=.020",
          "SET_VELOCITY_LIMIT SQUARE_CORNER_VELOCITY=1 ACCEL=500",
          "TUNING_TOWER COMMAND=SET_PRESSURE_ADVANCE PARAMETER=ADVANCE START=0 FACTOR=.020",
          "SET_VELOCITY_LIMIT SQUARE_CORNER_VELOCITY=1 ACCEL=500",
          "M300 S440 P200",
          "M300 S440 P200"
        ]
      },
      "layout": {
        "layouts": {
          "dashboard": {
            "container1": [
              {
                "id": "printer-status-card",
                "enabled": true,
                "collapsed": false
              },
              {
                "id": "camera-card",
                "enabled": true,
                "collapsed": false
              },
              {
                "id": "toolhead-card",
                "enabled": true,
                "collapsed": false
              },
              {
                "id": "macros-card",
                "enabled": true,
                "collapsed": false
              },
              {
                "id": "outputs-card",
                "enabled": true,
                "collapsed": false
              },
              {
                "id": "printer-limits-card",
                "enabled": true,
                "collapsed": false
              },
              {
                "id": "retract-card",
                "enabled": true,
                "collapsed": false
              }
            ]
          }
        }
      },
      "macros": {},
      "uiSettings": {
        "general": {
          "confirmOnEstop": true,
          "cameraFullscreenAction": "rawstream"
        }
      }
    }
  }
}
```

**Comment by AndreasReitberger** [comment]
Thanks for the quick respone. The "cameras" respone looks different on your end as on my end. I get the full settings from the cameras when calling this function.

It actually should hold following properties.

```cs
IEnumerable<KlipperDatabaseWebcamConfig> temp = fluiddObject.Cameras.Select(item => new KlipperDatabaseWebcamConfig()
                            {
                                Id = item.Id,
                                Enabled = item.Enabled,
                                Name = item.Name,
                                FlipX = item.FlipX,
                                FlipY = item.FlipY,
                                Service = item.Type,
                                TargetFps = item.Fpstarget,
                                Url = item.Url,
                            });
```
https://github.com/AndreasReitberger/KlipperRestApiSharp/blob/main/source/KlipperSharpWebApi/KlipperSharpWebApi/KlipperClient.cs#L6660

For testing, can you add a second camera in your fluidd settings? 
Just give it a different name and then repeat the first command.

**Comment by adrianocr** [comment]
@AndreasReitberger I added a second cam and repeated. The only thing that changes is the activeCamera value. I don't get any of the other keys you are looking for above.

I'm going to try mainsail later today and see if maybe that makes a difference.

**Comment by adrianocr** [comment]
Tried mainsail (docker containers are awesome). Unfortunately the app still didn't connect and apparently the "cameras" key isn't valid in the URL you wanted me to test

Sorry for all the difficulty on this, man

**Comment by AndreasReitberger** [comment]
Yes for MainsailOS add as namespace mainsail and as key webcam or webcams.
I will update the tool if no cameras are found, it will use the default url.

No worry, I'm glad to help. I'll let you know when the new version is ready.

Best,
Andreas

**Comment by AndreasReitberger** [comment]
Hi @adrianocr,

I published a fix which should fix your issue. I'll release a new app update soon. If the bug is not fixed for you, please open a new issue.
Thank you!

**Comment by AndreasReitberger** [comment]
Hi @adrianocr 
I just uploaded a new beta to TestFlight
https://testflight.apple.com/join/TyguKzt9

Once Apple has approved it, please test the new version. 
The webcam should now work for you :)

**Comment by adrianocr** [comment]
Awesome, thank you for looking into this.

And a quick suggestion; maybe allow the webcam URL to get input manually? That is how it works in mobileraker. I manually specify http://192.168.0.5/webcam?action=stream and presto
